import { AppDataSource } from "../src/data-source";
import { Broadcast } from "../src/entities/Broadcast";

const broadcasts = [
  {
    store: { id: 1 },
    matchDate: "2025-06-30",
    matchTime: "20:00",
    sport: { id: 1 },
    league: { id: 1 },
    teamOne: "맨유",
    teamTwo: "리버풀",
    etc: "빅매치",
  },
  {
    store: { id: 2 },
    matchDate: "2025-06-28",
    matchTime: "18:00",
    sport: { id: 2 },
    league: { id: 10 },
    teamOne: "LG 트윈스",
    teamTwo: "두산 베어스",
    etc: "잠실 라이벌전",
  },
  {
    store: { id: 3 },
    matchDate: "2025-07-01",
    matchTime: "19:30",
    sport: { id: 3 },
    league: { id: 15 },
    teamOne: "골든스테이트 워리어스",
    teamTwo: "LA 레이커스",
    etc: "NBA 빅매치",
  },
  {
    store: { id: 4 },
    matchDate: "2025-07-02",
    matchTime: "17:00",
    sport: { id: 4 },
    league: { id: 18 },
    teamOne: "흥국생명 핑크스파이더스",
    teamTwo: "현대건설 힐스테이트",
    etc: "V-리그 여자부",
  },
  {
    store: { id: 5 },
    matchDate: "2025-07-03",
    matchTime: "14:00",
    sport: { id: 2 },
    league: { id: 10 },
    teamOne: "롯데 자이언츠",
    teamTwo: "삼성 라이온즈",
    etc: "사직 빅매치",
  },
  {
    store: { id: 6 },
    matchDate: "2025-07-04",
    matchTime: "20:00",
    sport: { id: 1 },
    league: { id: 6 },
    teamOne: "바르셀로나",
    teamTwo: "레알 마드리드",
    etc: "엘 클라시코",
  },
  {
    store: { id: 7 },
    matchDate: "2025-07-05",
    matchTime: "18:00",
    sport: { id: 7 },
    league: { id: 27 },
    teamOne: "T1",
    teamTwo: "젠지",
    etc: "LCK 결승전",
  },
  {
    store: { id: 8 },
    matchDate: "2025-07-06",
    matchTime: "20:30",
    sport: { id: 1 },
    league: { id: 5 },
    teamOne: "AC 밀란",
    teamTwo: "인터 밀란",
    etc: "밀라노 더비",
  },
  {
    store: { id: 9 },
    matchDate: "2025-07-07",
    matchTime: "19:00",
    sport: { id: 2 },
    league: { id: 11 },
    teamOne: "뉴욕 양키스",
    teamTwo: "보스턴 레드삭스",
    etc: "MLB 전통 라이벌전",
  },
  {
    store: { id: 10 },
    matchDate: "2025-07-08",
    matchTime: "21:00",
    sport: { id: 3 },
    league: { id: 15 },
    teamOne: "마이애미 히트",
    teamTwo: "덴버 너게츠",
    etc: "NBA 파이널 리매치",
  },
  {
    store: { id: 11 },
    matchDate: "2025-07-09",
    matchTime: "18:00",
    sport: { id: 4 },
    league: { id: 19 },
    teamOne: "대한항공 점보스",
    teamTwo: "OK금융그룹 읏맨",
    etc: "V-리그 남자부",
  },
  {
    store: { id: 12 },
    matchDate: "2025-07-10",
    matchTime: "16:00",
    sport: { id: 7 },
    league: { id: 27 },
    teamOne: "KT 롤스터",
    teamTwo: "DRX",
    etc: "LCK 정규시즌",
  },
  {
    store: { id: 13 },
    matchDate: "2025-07-11",
    matchTime: "20:00",
    sport: { id: 1 },
    league: { id: 9 },
    teamOne: "첼시",
    teamTwo: "아스널",
    etc: "런던 더비",
  },
  {
    store: { id: 14 },
    matchDate: "2025-07-12",
    matchTime: "20:00",
    sport: { id: 1 }, 
    league: { id: 1 },
    teamOne: "맨유",
    teamTwo: "리버풀",
    etc: "주말 리매치",
  },
  {
    store: { id: 15 },
    matchDate: "2025-07-13",
    matchTime: "18:00",
    sport: { id: 7 },
    league: { id: 27 }, 
    teamOne: "T1",
    teamTwo: "젠지",
    etc: "서머 시즌 리벤지 매치",
  },
];

export const seedBroadcasts = async () => {
  const broadcastRepo = AppDataSource.getRepository(Broadcast);

  for (const item of broadcasts) {
    const broadcast = broadcastRepo.create(item);
    await broadcastRepo.save(broadcast);
  }

  console.log("✅ 중계 일정 시드 완료");
};
